obj-$(CONFIG_PLATFORM_PINKY)	+= eeprom.o
#obj-$(CONFIG_PLATFORM_PINKY)	+= gpio.o
obj-$(CONFIG_PLATFORM_PINKY)	+= memory.o
obj-$(CONFIG_PLATFORM_PINKY)	+= psu.o
obj-$(CONFIG_PLATFORM_PINKY)	+= sys.o
obj-$(CONFIG_PLATFORM_PINKY)	+= pinky.o
