obj-$(CONFIG_PLATFORM_LINK)	+= ec.o
obj-$(CONFIG_PLATFORM_LINK)	+= eeprom.o
obj-$(CONFIG_PLATFORM_LINK)	+= gpio.o
obj-$(CONFIG_PLATFORM_LINK)	+= link.o
obj-$(CONFIG_PLATFORM_LINK)	+= memory.o
obj-$(CONFIG_PLATFORM_LINK)	+= nvram.o
obj-$(CONFIG_PLATFORM_LINK)	+= sys.o
