obj-$(CONFIG_ACER_CHROMIA700)	+= chromia700.o
obj-$(CONFIG_ACER_CHROMIA700)	+= ec.o
obj-$(CONFIG_ACER_CHROMIA700)	+= eeprom.o
obj-$(CONFIG_ACER_CHROMIA700)	+= gpio.o
obj-$(CONFIG_ACER_CHROMIA700)	+= memory.o
obj-$(CONFIG_ACER_CHROMIA700)	+= nvram.o
obj-$(CONFIG_ACER_CHROMIA700)	+= sys.o
obj-$(CONFIG_ACER_CHROMIA700)	+= vpd.o
