obj-$(CONFIG_PLATFORM_STOUT)	+= battery.o
obj-$(CONFIG_PLATFORM_STOUT)	+= ec.o
obj-$(CONFIG_PLATFORM_STOUT)	+= eeprom.o
obj-$(CONFIG_PLATFORM_STOUT)	+= memory.o
obj-$(CONFIG_PLATFORM_STOUT)	+= nvram.o
obj-$(CONFIG_PLATFORM_STOUT)	+= storage.o
obj-$(CONFIG_PLATFORM_STOUT)	+= stout.o
obj-$(CONFIG_PLATFORM_STOUT)	+= sys.o
