obj-$(CONFIG_PLATFORM_BELTINO)	+= eeprom.o
obj-$(CONFIG_PLATFORM_BELTINO)	+= gpio.o
obj-$(CONFIG_PLATFORM_BELTINO)	+= memory.o
obj-$(CONFIG_PLATFORM_BELTINO)	+= nvram.o
obj-$(CONFIG_PLATFORM_BELTINO)	+= sensors.o
obj-$(CONFIG_PLATFORM_BELTINO)	+= sys.o
obj-$(CONFIG_PLATFORM_BELTINO)	+= beltino.o
