obj-$(CONFIG_GOOGLE_CR48)	+= cr48.o
obj-$(CONFIG_GOOGLE_CR48)	+= ec.o
obj-$(CONFIG_GOOGLE_CR48)	+= eeprom.o
obj-$(CONFIG_GOOGLE_CR48)	+= gpio.o
obj-$(CONFIG_GOOGLE_CR48)	+= memory.o
#obj-$(CONFIG_GOOGLE_CR48)	+= nvram.o
obj-$(CONFIG_GOOGLE_CR48)	+= sys.o
obj-$(CONFIG_GOOGLE_CR48)	+= vpd.o
