obj-$(CONFIG_PLATFORM_SLIPPY)	+= ec.o
obj-$(CONFIG_PLATFORM_SLIPPY)	+= eeprom.o
obj-$(CONFIG_PLATFORM_SLIPPY)	+= gpio.o
obj-$(CONFIG_PLATFORM_SLIPPY)	+= memory.o
obj-$(CONFIG_PLATFORM_SLIPPY)	+= nvram.o
obj-$(CONFIG_PLATFORM_SLIPPY)	+= sys.o
obj-$(CONFIG_PLATFORM_SLIPPY)	+= slippy.o
