obj-$(CONFIG_PLATFORM_GLADOS)	+= eeprom.o
#obj-$(CONFIG_PLATFORM_GLADOS)	+= gpio.o
obj-$(CONFIG_PLATFORM_GLADOS)	+= memory.o
obj-$(CONFIG_PLATFORM_GLADOS)	+= nvram.o
obj-$(CONFIG_PLATFORM_GLADOS)	+= sys.o
obj-$(CONFIG_PLATFORM_GLADOS)	+= glados.o
