obj-$(CONFIG_PLATFORM_SPRING)	+= ec.o
obj-$(CONFIG_PLATFORM_SPRING)	+= eeprom.o
obj-$(CONFIG_PLATFORM_SPRING)	+= gpio.o
obj-$(CONFIG_PLATFORM_SPRING)	+= memory.o
obj-$(CONFIG_PLATFORM_SPRING)	+= sys.o
obj-$(CONFIG_PLATFORM_SPRING)	+= spring.o
