obj-$(CONFIG_PLATFORM_AURON)	+= eeprom.o
obj-$(CONFIG_PLATFORM_AURON)	+= gpio.o
obj-$(CONFIG_PLATFORM_AURON)	+= memory.o
obj-$(CONFIG_PLATFORM_AURON)	+= nvram.o
obj-$(CONFIG_PLATFORM_AURON)	+= sys.o
obj-$(CONFIG_PLATFORM_AURON)	+= auron.o
