obj-$(CONFIG_PLATFORM_MARIO)	+= cr48.o
obj-$(CONFIG_PLATFORM_MARIO)	+= ec.o
obj-$(CONFIG_PLATFORM_MARIO)	+= eeprom.o
obj-$(CONFIG_PLATFORM_MARIO)	+= gpio.o
obj-$(CONFIG_PLATFORM_MARIO)	+= memory.o
#obj-$(CONFIG_PLATFORM_MARIO)	+= nvram.o
obj-$(CONFIG_PLATFORM_MARIO)	+= sys.o
obj-$(CONFIG_PLATFORM_MARIO)	+= vpd.o
