obj-$(CONFIG_PLATFORM_PEACH_PIT)	+= ec.o
obj-$(CONFIG_PLATFORM_PEACH_PIT)	+= eeprom.o
obj-$(CONFIG_PLATFORM_PEACH_PIT)	+= gpio.o
obj-$(CONFIG_PLATFORM_PEACH_PIT)	+= memory.o
obj-$(CONFIG_PLATFORM_PEACH_PIT)	+= sys.o
obj-$(CONFIG_PLATFORM_PEACH_PIT)	+= peach_pit.o
