obj-$(CONFIG_PLATFORM_CYAN)	+= eeprom.o
obj-$(CONFIG_PLATFORM_CYAN)	+= gpio.o
obj-$(CONFIG_PLATFORM_CYAN)	+= memory.o
obj-$(CONFIG_PLATFORM_CYAN)	+= nvram.o
obj-$(CONFIG_PLATFORM_CYAN)	+= sys.o
obj-$(CONFIG_PLATFORM_CYAN)	+= cyan.o
