obj-$(CONFIG_SAMSUNG_SERIES5)	+= ec.o
obj-$(CONFIG_SAMSUNG_SERIES5)	+= eeprom.o
obj-$(CONFIG_SAMSUNG_SERIES5)	+= gpio.o
obj-$(CONFIG_SAMSUNG_SERIES5)	+= memory.o
#obj-$(CONFIG_SAMSUNG_SERIES5)	+= nvram.o
obj-$(CONFIG_SAMSUNG_SERIES5)	+= series5.o
obj-$(CONFIG_SAMSUNG_SERIES5)	+= sys.o
obj-$(CONFIG_SAMSUNG_SERIES5)	+= vpd.o
