obj-$(CONFIG_PLATFORM_NYAN)	+= ec.o
obj-$(CONFIG_PLATFORM_NYAN)	+= eeprom.o
obj-$(CONFIG_PLATFORM_NYAN)	+= memory.o
obj-$(CONFIG_PLATFORM_NYAN)	+= psu.o
obj-$(CONFIG_PLATFORM_NYAN)	+= sys.o
obj-$(CONFIG_PLATFORM_NYAN)	+= nyan.o
