obj-$(CONFIG_PLATFORM_PEACH)	+= ec.o
obj-$(CONFIG_PLATFORM_PEACH)	+= eeprom.o
obj-$(CONFIG_PLATFORM_PEACH)	+= gpio.o
obj-$(CONFIG_PLATFORM_PEACH)	+= memory.o
obj-$(CONFIG_PLATFORM_PEACH)	+= sys.o
obj-$(CONFIG_PLATFORM_PEACH)	+= peach.o
