obj-$(CONFIG_PLATFORM_FIZZ)	+= eeprom.o
#obj-$(CONFIG_PLATFORM_FIZZ)	+= gpio.o
obj-$(CONFIG_PLATFORM_FIZZ)	+= memory.o
obj-$(CONFIG_PLATFORM_FIZZ)	+= nvram.o
obj-$(CONFIG_PLATFORM_FIZZ)	+= sys.o
obj-$(CONFIG_PLATFORM_FIZZ)	+= fizz.o
