obj-$(CONFIG_PLATFORM_DEFAULT)		+= default/
obj-$(CONFIG_PLATFORM_EXPERIMENTAL)	+= experimental/
obj-$(CONFIG_PLATFORM_ACER)		+= acer/
obj-$(CONFIG_PLATFORM_HP)		+= hp/
obj-$(CONFIG_PLATFORM_GOOGLE)		+= google/
obj-$(CONFIG_PLATFORM_SAMSUNG)		+= samsung/

obj-y					+= platform_list.o
