obj-$(CONFIG_PLATFORM_ZGB)	+= chromia700.o
obj-$(CONFIG_PLATFORM_ZGB)	+= ec.o
obj-$(CONFIG_PLATFORM_ZGB)	+= eeprom.o
obj-$(CONFIG_PLATFORM_ZGB)	+= gpio.o
obj-$(CONFIG_PLATFORM_ZGB)	+= memory.o
obj-$(CONFIG_PLATFORM_ZGB)	+= nvram.o
obj-$(CONFIG_PLATFORM_ZGB)	+= sys.o
obj-$(CONFIG_PLATFORM_ZGB)	+= vpd.o
