# always decend into the subdirectories
obj-y	+= cypress/
obj-y	+= google/
obj-y	+= intel/
obj-y	+= ite/
obj-y	+= nuvoton/
obj-y	+= smsc/

obj-y	+= gpio.o
obj-y	+= superio.o	# FIXME: should this depend on PLATFORM_ARCH_X86?
