obj-$(CONFIG_PLATFORM_STORM)	+= eeprom.o
#obj-$(CONFIG_PLATFORM_STORM)	+= gpio.o
#obj-$(CONFIG_PLATFORM_STORM)	+= memory.o
obj-$(CONFIG_PLATFORM_STORM)	+= sys.o
obj-$(CONFIG_PLATFORM_STORM)	+= storm.o
