obj-$(CONFIG_CHIPSET_INTEL)			+= ich_generic.o ich_gpio.o
obj-$(CONFIG_CHIPSET_INTEL)			+= lpss_generic.o lpss_gpio.o
obj-$(CONFIG_CHIPSET_INTEL_NM10)		+= nm10/
obj-$(CONFIG_CHIPSET_INTEL_SERIES6)		+= series6/
obj-$(CONFIG_CHIPSET_INTEL_LYNXPOINT_LP)	+= lynxpoint_lp/
obj-$(CONFIG_SOC_INTEL_BAYTRAIL)		+= baytrail/
obj-$(CONFIG_SOC_INTEL_BRASWELL)		+= braswell/
