obj-$(CONFIG_PLATFORM_PARROT)	+= eeprom.o
obj-$(CONFIG_PLATFORM_PARROT)	+= memory.o
obj-$(CONFIG_PLATFORM_PARROT)	+= nvram.o
obj-$(CONFIG_PLATFORM_PARROT)	+= parrot.o
obj-$(CONFIG_PLATFORM_PARROT)	+= sys.o
obj-$(CONFIG_PLATFORM_PARROT)	+= vpd.o
obj-$(CONFIG_PLATFORM_PARROT)	+= ec.o
