obj-$(CONFIG_PLATFORM_SKATE)	+= ec.o
obj-$(CONFIG_PLATFORM_SKATE)	+= eeprom.o
obj-$(CONFIG_PLATFORM_SKATE)	+= gpio.o
obj-$(CONFIG_PLATFORM_SKATE)	+= memory.o
obj-$(CONFIG_PLATFORM_SKATE)	+= sys.o
obj-$(CONFIG_PLATFORM_SKATE)	+= skate.o
