obj-$(CONFIG_PLATFORM_SAMUS)	+= eeprom.o
obj-$(CONFIG_PLATFORM_SAMUS)	+= gpio.o
obj-$(CONFIG_PLATFORM_SAMUS)	+= memory.o
obj-$(CONFIG_PLATFORM_SAMUS)	+= nvram.o
obj-$(CONFIG_PLATFORM_SAMUS)	+= sys.o
obj-$(CONFIG_PLATFORM_SAMUS)	+= samus.o
