obj-$(CONFIG_PLATFORM_STRAGO)	+= eeprom.o
obj-$(CONFIG_PLATFORM_STRAGO)	+= gpio.o
obj-$(CONFIG_PLATFORM_STRAGO)	+= memory.o
obj-$(CONFIG_PLATFORM_STRAGO)	+= nvram.o
obj-$(CONFIG_PLATFORM_STRAGO)	+= sys.o
obj-$(CONFIG_PLATFORM_STRAGO)	+= strago.o
