# Note: vpd_encode.c contains main() and will be compiled at the end

obj-$(CONFIG_BUILD_AGZ_VENDOR_VPD_BLOB_V3)		+= agz_blob.o
obj-$(CONFIG_BUILD_AGZ_VENDOR_VPD_BLOB_V5)		+= agz_blob.o
obj-y							+= google_blob.o
