obj-$(CONFIG_PLATFORM_RAMBI)	+= ec.o
obj-$(CONFIG_PLATFORM_RAMBI)	+= eeprom.o
obj-$(CONFIG_PLATFORM_RAMBI)	+= gpio.o
obj-$(CONFIG_PLATFORM_RAMBI)	+= memory.o
obj-$(CONFIG_PLATFORM_RAMBI)	+= nvram.o
obj-$(CONFIG_PLATFORM_RAMBI)	+= psu.o
obj-$(CONFIG_PLATFORM_RAMBI)	+= sys.o
obj-$(CONFIG_PLATFORM_RAMBI)	+= rambi.o
