obj-$(CONFIG_PLATFORM_ALEX)	+= ec.o
obj-$(CONFIG_PLATFORM_ALEX)	+= eeprom.o
obj-$(CONFIG_PLATFORM_ALEX)	+= gpio.o
obj-$(CONFIG_PLATFORM_ALEX)	+= memory.o
#obj-$(CONFIG_PLATFORM_ALEX)	+= nvram.o
obj-$(CONFIG_PLATFORM_ALEX)	+= series5.o
obj-$(CONFIG_PLATFORM_ALEX)	+= sys.o
obj-$(CONFIG_PLATFORM_ALEX)	+= vpd.o
