obj-$(CONFIG_CROS_EC)		+= cros_ec.o
obj-$(CONFIG_CROS_EC)		+= cros_ec_cb.o
obj-$(CONFIG_CROS_EC)		+= cros_ec_dev.o
obj-$(CONFIG_CROS_EC)		+= cros_ec_lock.o
obj-$(CONFIG_CROS_EC_I2C)	+= cros_ec_i2c.o
obj-$(CONFIG_CROS_EC_LPC)	+= cros_ec_lpc.o
