obj-$(CONFIG_PLATFORM_DAISY)	+= ec.o
obj-$(CONFIG_PLATFORM_DAISY)	+= eeprom.o
obj-$(CONFIG_PLATFORM_DAISY)	+= gpio.o
obj-$(CONFIG_PLATFORM_DAISY)	+= memory.o
obj-$(CONFIG_PLATFORM_DAISY)	+= sys.o
obj-$(CONFIG_PLATFORM_DAISY)	+= daisy.o
